use crate::state::AppState;
use eframe::egui::{self, Color32, CornerRadius, Key, Rect, Vec2};

struct KeyDef {
    row: usize,
    col: f32,
    width: f32,
    label: &'static str,
    key: Option<Key>,
}

const UNIT: f32 = 52.0;
const KEY_H: f32 = 44.0;
const GAP: f32 = 4.0;

fn layout() -> Vec<KeyDef> {
    vec![
        KeyDef {
            row: 0,
            col: 0.0,
            width: 1.0,
            label: "Esc",
            key: Some(Key::Escape),
        },
        KeyDef {
            row: 0,
            col: 2.0,
            width: 1.0,
            label: "F1",
            key: Some(Key::F1),
        },
        KeyDef {
            row: 0,
            col: 3.0,
            width: 1.0,
            label: "F2",
            key: Some(Key::F2),
        },
        KeyDef {
            row: 0,
            col: 4.0,
            width: 1.0,
            label: "F3",
            key: Some(Key::F3),
        },
        KeyDef {
            row: 0,
            col: 5.0,
            width: 1.0,
            label: "F4",
            key: Some(Key::F4),
        },
        KeyDef {
            row: 0,
            col: 6.5,
            width: 1.0,
            label: "F5",
            key: Some(Key::F5),
        },
        KeyDef {
            row: 0,
            col: 7.5,
            width: 1.0,
            label: "F6",
            key: Some(Key::F6),
        },
        KeyDef {
            row: 0,
            col: 8.5,
            width: 1.0,
            label: "F7",
            key: Some(Key::F7),
        },
        KeyDef {
            row: 0,
            col: 9.5,
            width: 1.0,
            label: "F8",
            key: Some(Key::F8),
        },
        KeyDef {
            row: 0,
            col: 11.0,
            width: 1.0,
            label: "F9",
            key: Some(Key::F9),
        },
        KeyDef {
            row: 0,
            col: 12.0,
            width: 1.0,
            label: "F10",
            key: Some(Key::F10),
        },
        KeyDef {
            row: 0,
            col: 13.0,
            width: 1.0,
            label: "F11",
            key: Some(Key::F11),
        },
        KeyDef {
            row: 0,
            col: 14.0,
            width: 1.0,
            label: "F12",
            key: Some(Key::F12),
        },
        KeyDef {
            row: 0,
            col: 15.0,
            width: 1.0,
            label: "PrtSc",
            key: None,
        },
        KeyDef {
            row: 0,
            col: 16.0,
            width: 1.0,
            label: "ScrLk",
            key: None,
        },
        KeyDef {
            row: 0,
            col: 17.0,
            width: 1.0,
            label: "Pause",
            key: None,
        },
        KeyDef {
            row: 1,
            col: 0.0,
            width: 1.0,
            label: "~",
            key: Some(Key::Backtick),
        },
        KeyDef {
            row: 1,
            col: 1.0,
            width: 1.0,
            label: "1",
            key: Some(Key::Num1),
        },
        KeyDef {
            row: 1,
            col: 2.0,
            width: 1.0,
            label: "2",
            key: Some(Key::Num2),
        },
        KeyDef {
            row: 1,
            col: 3.0,
            width: 1.0,
            label: "3",
            key: Some(Key::Num3),
        },
        KeyDef {
            row: 1,
            col: 4.0,
            width: 1.0,
            label: "4",
            key: Some(Key::Num4),
        },
        KeyDef {
            row: 1,
            col: 5.0,
            width: 1.0,
            label: "5",
            key: Some(Key::Num5),
        },
        KeyDef {
            row: 1,
            col: 6.0,
            width: 1.0,
            label: "6",
            key: Some(Key::Num6),
        },
        KeyDef {
            row: 1,
            col: 7.0,
            width: 1.0,
            label: "7",
            key: Some(Key::Num7),
        },
        KeyDef {
            row: 1,
            col: 8.0,
            width: 1.0,
            label: "8",
            key: Some(Key::Num8),
        },
        KeyDef {
            row: 1,
            col: 9.0,
            width: 1.0,
            label: "9",
            key: Some(Key::Num9),
        },
        KeyDef {
            row: 1,
            col: 10.0,
            width: 1.0,
            label: "0",
            key: Some(Key::Num0),
        },
        KeyDef {
            row: 1,
            col: 11.0,
            width: 1.0,
            label: "-",
            key: Some(Key::Minus),
        },
        KeyDef {
            row: 1,
            col: 12.0,
            width: 1.0,
            label: "=",
            key: Some(Key::Equals),
        },
        KeyDef {
            row: 1,
            col: 13.0,
            width: 2.0,
            label: "Back",
            key: Some(Key::Backspace),
        },
        KeyDef {
            row: 1,
            col: 15.0,
            width: 1.0,
            label: "Ins",
            key: Some(Key::Insert),
        },
        KeyDef {
            row: 1,
            col: 16.0,
            width: 1.0,
            label: "Home",
            key: Some(Key::Home),
        },
        KeyDef {
            row: 1,
            col: 17.0,
            width: 1.0,
            label: "PgUp",
            key: Some(Key::PageUp),
        },
        KeyDef {
            row: 2,
            col: 0.0,
            width: 1.5,
            label: "Tab",
            key: Some(Key::Tab),
        },
        KeyDef {
            row: 2,
            col: 1.5,
            width: 1.0,
            label: "Q",
            key: Some(Key::Q),
        },
        KeyDef {
            row: 2,
            col: 2.5,
            width: 1.0,
            label: "W",
            key: Some(Key::W),
        },
        KeyDef {
            row: 2,
            col: 3.5,
            width: 1.0,
            label: "E",
            key: Some(Key::E),
        },
        KeyDef {
            row: 2,
            col: 4.5,
            width: 1.0,
            label: "R",
            key: Some(Key::R),
        },
        KeyDef {
            row: 2,
            col: 5.5,
            width: 1.0,
            label: "T",
            key: Some(Key::T),
        },
        KeyDef {
            row: 2,
            col: 6.5,
            width: 1.0,
            label: "Y",
            key: Some(Key::Y),
        },
        KeyDef {
            row: 2,
            col: 7.5,
            width: 1.0,
            label: "U",
            key: Some(Key::U),
        },
        KeyDef {
            row: 2,
            col: 8.5,
            width: 1.0,
            label: "I",
            key: Some(Key::I),
        },
        KeyDef {
            row: 2,
            col: 9.5,
            width: 1.0,
            label: "O",
            key: Some(Key::O),
        },
        KeyDef {
            row: 2,
            col: 10.5,
            width: 1.0,
            label: "P",
            key: Some(Key::P),
        },
        KeyDef {
            row: 2,
            col: 11.5,
            width: 1.0,
            label: "[",
            key: Some(Key::OpenBracket),
        },
        KeyDef {
            row: 2,
            col: 12.5,
            width: 1.0,
            label: "]",
            key: Some(Key::CloseBracket),
        },
        KeyDef {
            row: 2,
            col: 13.5,
            width: 1.5,
            label: "\\",
            key: Some(Key::Backslash),
        },
        KeyDef {
            row: 2,
            col: 15.0,
            width: 1.0,
            label: "Del",
            key: Some(Key::Delete),
        },
        KeyDef {
            row: 2,
            col: 16.0,
            width: 1.0,
            label: "End",
            key: Some(Key::End),
        },
        KeyDef {
            row: 2,
            col: 17.0,
            width: 1.0,
            label: "PgDn",
            key: Some(Key::PageDown),
        },
        KeyDef {
            row: 3,
            col: 0.0,
            width: 1.75,
            label: "Caps",
            key: None,
        },
        KeyDef {
            row: 3,
            col: 1.75,
            width: 1.0,
            label: "A",
            key: Some(Key::A),
        },
        KeyDef {
            row: 3,
            col: 2.75,
            width: 1.0,
            label: "S",
            key: Some(Key::S),
        },
        KeyDef {
            row: 3,
            col: 3.75,
            width: 1.0,
            label: "D",
            key: Some(Key::D),
        },
        KeyDef {
            row: 3,
            col: 4.75,
            width: 1.0,
            label: "F",
            key: Some(Key::F),
        },
        KeyDef {
            row: 3,
            col: 5.75,
            width: 1.0,
            label: "G",
            key: Some(Key::G),
        },
        KeyDef {
            row: 3,
            col: 6.75,
            width: 1.0,
            label: "H",
            key: Some(Key::H),
        },
        KeyDef {
            row: 3,
            col: 7.75,
            width: 1.0,
            label: "J",
            key: Some(Key::J),
        },
        KeyDef {
            row: 3,
            col: 8.75,
            width: 1.0,
            label: "K",
            key: Some(Key::K),
        },
        KeyDef {
            row: 3,
            col: 9.75,
            width: 1.0,
            label: "L",
            key: Some(Key::L),
        },
        KeyDef {
            row: 3,
            col: 10.75,
            width: 1.0,
            label: ";",
            key: Some(Key::Semicolon),
        },
        KeyDef {
            row: 3,
            col: 11.75,
            width: 1.0,
            label: "'",
            key: Some(Key::Quote),
        },
        KeyDef {
            row: 3,
            col: 12.75,
            width: 2.25,
            label: "Enter",
            key: Some(Key::Enter),
        },
        KeyDef {
            row: 4,
            col: 0.0,
            width: 2.25,
            label: "Shift",
            key: None,
        },
        KeyDef {
            row: 4,
            col: 2.25,
            width: 1.0,
            label: "Z",
            key: Some(Key::Z),
        },
        KeyDef {
            row: 4,
            col: 3.25,
            width: 1.0,
            label: "X",
            key: Some(Key::X),
        },
        KeyDef {
            row: 4,
            col: 4.25,
            width: 1.0,
            label: "C",
            key: Some(Key::C),
        },
        KeyDef {
            row: 4,
            col: 5.25,
            width: 1.0,
            label: "V",
            key: Some(Key::V),
        },
        KeyDef {
            row: 4,
            col: 6.25,
            width: 1.0,
            label: "B",
            key: Some(Key::B),
        },
        KeyDef {
            row: 4,
            col: 7.25,
            width: 1.0,
            label: "N",
            key: Some(Key::N),
        },
        KeyDef {
            row: 4,
            col: 8.25,
            width: 1.0,
            label: "M",
            key: Some(Key::M),
        },
        KeyDef {
            row: 4,
            col: 9.25,
            width: 1.0,
            label: ",",
            key: Some(Key::Comma),
        },
        KeyDef {
            row: 4,
            col: 10.25,
            width: 1.0,
            label: ".",
            key: Some(Key::Period),
        },
        KeyDef {
            row: 4,
            col: 11.25,
            width: 1.0,
            label: "/",
            key: Some(Key::Slash),
        },
        KeyDef {
            row: 4,
            col: 12.25,
            width: 2.75,
            label: "Shift",
            key: None,
        },
        KeyDef {
            row: 4,
            col: 16.0,
            width: 1.0,
            label: "^",
            key: Some(Key::ArrowUp),
        },
        KeyDef {
            row: 5,
            col: 0.0,
            width: 1.25,
            label: "Ctrl",
            key: None,
        },
        KeyDef {
            row: 5,
            col: 1.25,
            width: 1.25,
            label: "Win",
            key: None,
        },
        KeyDef {
            row: 5,
            col: 2.5,
            width: 1.25,
            label: "Alt",
            key: None,
        },
        KeyDef {
            row: 5,
            col: 3.75,
            width: 6.25,
            label: "",
            key: Some(Key::Space),
        },
        KeyDef {
            row: 5,
            col: 10.0,
            width: 1.25,
            label: "Alt",
            key: None,
        },
        KeyDef {
            row: 5,
            col: 11.25,
            width: 1.25,
            label: "Win",
            key: None,
        },
        KeyDef {
            row: 5,
            col: 12.5,
            width: 1.25,
            label: "Menu",
            key: None,
        },
        KeyDef {
            row: 5,
            col: 13.75,
            width: 1.25,
            label: "Ctrl",
            key: None,
        },
        KeyDef {
            row: 5,
            col: 15.0,
            width: 1.0,
            label: "<",
            key: Some(Key::ArrowLeft),
        },
        KeyDef {
            row: 5,
            col: 16.0,
            width: 1.0,
            label: "v",
            key: Some(Key::ArrowDown),
        },
        KeyDef {
            row: 5,
            col: 17.0,
            width: 1.0,
            label: ">",
            key: Some(Key::ArrowRight),
        },
        KeyDef {
            row: 0,
            col: 19.0,
            width: 1.0,
            label: "Num",
            key: None,
        },
        KeyDef {
            row: 0,
            col: 20.0,
            width: 1.0,
            label: "/",
            key: None,
        },
        KeyDef {
            row: 0,
            col: 21.0,
            width: 1.0,
            label: "*",
            key: None,
        },
        KeyDef {
            row: 0,
            col: 22.0,
            width: 1.0,
            label: "-",
            key: None,
        },
        KeyDef {
            row: 1,
            col: 19.0,
            width: 1.0,
            label: "7",
            key: None,
        },
        KeyDef {
            row: 1,
            col: 20.0,
            width: 1.0,
            label: "8",
            key: None,
        },
        KeyDef {
            row: 1,
            col: 21.0,
            width: 1.0,
            label: "9",
            key: None,
        },
        KeyDef {
            row: 1,
            col: 22.0,
            width: 1.0,
            label: "+",
            key: None,
        },
        KeyDef {
            row: 2,
            col: 19.0,
            width: 1.0,
            label: "4",
            key: None,
        },
        KeyDef {
            row: 2,
            col: 20.0,
            width: 1.0,
            label: "5",
            key: None,
        },
        KeyDef {
            row: 2,
            col: 21.0,
            width: 1.0,
            label: "6",
            key: None,
        },
        KeyDef {
            row: 3,
            col: 19.0,
            width: 1.0,
            label: "1",
            key: None,
        },
        KeyDef {
            row: 3,
            col: 20.0,
            width: 1.0,
            label: "2",
            key: None,
        },
        KeyDef {
            row: 3,
            col: 21.0,
            width: 1.0,
            label: "3",
            key: None,
        },
        KeyDef {
            row: 3,
            col: 22.0,
            width: 1.0,
            label: "Ent",
            key: None,
        },
        KeyDef {
            row: 4,
            col: 19.0,
            width: 2.0,
            label: "0",
            key: None,
        },
        KeyDef {
            row: 4,
            col: 21.0,
            width: 1.0,
            label: ".",
            key: None,
        },
    ]
}

pub fn draw_keyboard(ui: &mut egui::Ui, state: &AppState) {
    let keys = layout();
    let total_w = 24.0 * (UNIT + GAP);
    let total_h = 11.0 * (KEY_H + GAP);

    let (response, painter) =
        ui.allocate_painter(Vec2::new(total_w, total_h + GAP), egui::Sense::hover());

    for kd in &keys {
        let x = response.rect.min.x + GAP + kd.col * (UNIT + GAP);
        let y = response.rect.min.y + GAP + kd.row as f32 * (KEY_H + GAP);
        let w = kd.width * (UNIT + GAP) - GAP;

        let key_rect = Rect::from_min_size(egui::pos2(x, y), Vec2::new(w, KEY_H));

        let pressed = kd
            .key
            .and_then(|k| state.keys.get(&k))
            .is_some_and(|ks| ks.pressed);
        let bg = if pressed {
            Color32::from_rgb(60, 180, 255)
        } else {
            Color32::from_gray(45)
        };
        let border = if pressed {
            Color32::from_rgb(100, 220, 255)
        } else {
            Color32::from_gray(70)
        };

        painter.rect(
            key_rect,
            CornerRadius::same(4),
            bg,
            egui::Stroke::new(1.0, border),
            egui::StrokeKind::Inside,
        );

        if !kd.label.is_empty() {
            painter.text(
                key_rect.center(),
                egui::Align2::CENTER_CENTER,
                kd.label,
                egui::FontId::proportional(13.0),
                Color32::WHITE,
            );
        }
    }
}
